apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGO_URI
          value: {{ .Values.backend.mongoUri | quote }}
        - name: HASH_KEY
          value: {{ .Values.backend.hashKey | quote }}
        - name: JWT_SECRET_KEY
          value: {{ .Values.backend.jwtSecretKey | quote }}
